spring.application.name=demo
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicExtractor=WARN
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=INFO
 
  spring.datasource.url=${SPRING_DATASOURCE_URL}
 spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
   spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


youtube.api.keys=${YOUTUBE_API_KEYS} # Plural

#spring.profiles.include=local
#SPRING_PROFILES_ACTIVE=prod

#logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG


# CONFIGURAÇÃO DE E-MAIL (GMAIL)
# spring.mail.host=smtp.gmail.com
# spring.mail.port=465
# spring.mail.username=${MAIL_USERNAME}
# spring.mail.password=${MAIL_PASSWORD}
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.ssl.enable=true
# spring.mail.properties.mail.smtp.connectiontimeout=10000
# spring.mail.properties.mail.smtp.timeout=10000
# spring.mail.properties.mail.smtp.writetimeout=10000

mailjet.api.key=${MAILJET_API_KEY}
mailjet.secret.key=${MAILJET_SECRET_KEY}